/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuestionario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JRadioButton;


/**
 *
 * @author juan_
 */
public class FormularioCuestionario extends javax.swing.JFrame {

   //Vamos a generar un List de radioButtons
    List<JRadioButton> radios=new ArrayList<>();
    
    
    public FormularioCuestionario() {
        initComponents();
       //Aqui dentro del constructor de nuestro formulario
       //invocamos nuesto metodo generarCuestionario()
       //LLenamos lo radios
       radios.add(radiotituloOpcion0);
       radios.add(radiotituloOpcion1);
       radios.add(radiotituloOpcion2);
       radios.add(radiotituloOpcion3);
       
       generarCuestionario();
        
    }
    //Aqui vamos a pegar el metodo
      public void generarCuestionario(){
        //Con el modelo construido debemos representar uestra pregunta
        //y mostrarala
        //Primero creamos las opciones
        Opcion op1 = new Opcion();
        op1.setTitulo("Londres");
        op1.setCorrecta(false);

        Opcion op2 = new Opcion();
        op2.setTitulo("Roma");
        op2.setCorrecta(false);

        Opcion op3 = new Opcion();
        op3.setTitulo("Paris");
        op3.setCorrecta(true);

        Opcion op4 = new Opcion();
        op4.setTitulo("Oslo");
        op4.setCorrecta(false);

        //Sigue el arreglo de opcion
        Opcion[] opciones = {op1, op2, op3, op4};
        Pregunta p1 = new Pregunta();
        p1.setTitulo("¿Cual es la capital de Francia");
        p1.setOpciones(opciones);

        //Vamos a adaptar el cuestioanario a lo que ya teniamos
        Cuestionario c = new Cuestionario();
        //Creamos el list de preguntas
        List<Pregunta> preguntas = new ArrayList<>();
        //Se agrega a este list la unica prgunta que tenemos
        preguntas.add(p1);
        //A este list le vamos a proporcionar el valor del correspondiente
        //cuestioanrio
        c.setPreguntas(preguntas);
//Primero ajustamos el titulo de la primer pregunta en la etiqueta de la preunta
  etiquetaTituloPregunta.setText(preguntas.get(0).getTitulo());
  //Llenamos con el modelo los radio buttons
  for(int i=0;i<radios.size();i++){
      radios.get(i).setText(preguntas.get(0).getOpciones()[i].getTitulo());
  }
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        etiquetaTituloPregunta = new javax.swing.JLabel();
        radiotituloOpcion0 = new javax.swing.JRadioButton();
        radiotituloOpcion1 = new javax.swing.JRadioButton();
        radiotituloOpcion2 = new javax.swing.JRadioButton();
        radiotituloOpcion3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTituloPregunta.setText("jLabel1");

        grupo.add(radiotituloOpcion0);
        radiotituloOpcion0.setText("jRadioButton1");

        grupo.add(radiotituloOpcion1);
        radiotituloOpcion1.setText("jRadioButton2");

        grupo.add(radiotituloOpcion2);
        radiotituloOpcion2.setText("jRadioButton3");

        grupo.add(radiotituloOpcion3);
        radiotituloOpcion3.setText("jRadioButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaTituloPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiotituloOpcion3)
                            .addComponent(radiotituloOpcion2)
                            .addComponent(radiotituloOpcion1)
                            .addComponent(radiotituloOpcion0))
                        .addGap(0, 320, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(etiquetaTituloPregunta)
                .addGap(18, 18, 18)
                .addComponent(radiotituloOpcion0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiotituloOpcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiotituloOpcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiotituloOpcion3)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaTituloPregunta;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JRadioButton radiotituloOpcion0;
    private javax.swing.JRadioButton radiotituloOpcion1;
    private javax.swing.JRadioButton radiotituloOpcion2;
    private javax.swing.JRadioButton radiotituloOpcion3;
    // End of variables declaration//GEN-END:variables
}
